logs:
  webex-log: "FastApi-logfile.log"

fastapi:
  host: "10.58.1.10" # use internal ip
  port: 8000

container_communication:
  host: "10.58.1.10" #use internal ip
  port: 5000
  secErrorWait: 60
  maxRetryError: 3
  maxConnect: 1 # at the moment only one is forced

logs:
  webex-log: "CosmFastapi-logfile.log"
